name: hdoc data pipeline

on:
  push:
    paths-ignore:
    - 'scripts/tweets.json'
    branches: [ main ]
  schedule:
    - cron: '35 16 * * *'

jobs:
  fetch-and-commit-tweets:
    runs-on: ubuntu-latest
    env:
      workdir: ./scripts
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      working-directory: ${{ env.workdir }}
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
        pip install -e .
    - name: Test with pytest
      working-directory: ${{ env.workdir }}
      run: |
        pytest --cov=hdoc_tracker --cov-report html tests
    - name: Fetch new tweets and push changes to GitHub
      working-directory: ${{ env.workdir }}
      run: |
        python hdoc_tracker/get_tweets.py
        python hdoc_tracker/commit_new_tweets.py
      env: # Set the secret as an input
        BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

  upload-tweets-to-upstash:
    needs: fetch-and-commit-tweets
    runs-on: ubuntu-latest
    env:
      workdir: ./uploader
    steps:
    - uses: actions/checkout@v2
    - name: Set up node 16
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - name: Install dependencies
      working-directory: ${{ env.workdir }}
      run: |
        yarn
    - name: upload data to upstash
      working-directory: ${{ env.workdir }}
      run: |
        yarn upstash
      env:
        UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
        UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
