name: tests

on: pull_request

jobs:
  ui-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "18.17.0"
      - name: Install dependencies
        run: yarn
      - name: Run UI tests
        run: yarn test:ci

  scripts-test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: .
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11.4"
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "latest"
      - name: Install dependencies
        working-directory: ./scripts
        run: poetry install
      - name: Run Python tests
        working-directory: ./scripts
        run: poetry run pytest
